# vim ft=yaml
# CI on Windows via appveyor

environment:
  global:
    BUILD_COMMIT: master
    NP_BUILD_DEP: "numpy==1.13"
    NP_TEST_DEP: "numpy==1.13"
    SP_DEP: "scipy"
    ANACONDA_ORG: "nipy"
    EXTRA_FLAGS: ""
    ANACONDA_SECRET:
      secure: Ds0PkQD0b/QOfoNoiPuFJb01zg0Mq0dkAxIG2jRXocCAereSXdWw6XYaDrutHWme


  matrix:
    - PYTHON: C:\Python27
    - PYTHON: C:\Python27-x64
      # Doctest fail from the Ls as in (1L, 2L) != (1, 2)
      EXTRA_FLAGS: "--without-doctest"
    - PYTHON: C:\Python36
    - PYTHON: C:\Python36-x64
    - PYTHON: C:\Python37
      NP_BUILD_DEP: "numpy==1.15"
      NP_TEST_DEP: "numpy==1.15"
    - PYTHON: C:\Python37-x64
      NP_BUILD_DEP: "numpy==1.15"
      NP_TEST_DEP: "numpy==1.15"
    - PYTHON: C:\Python38
      # https://stackoverflow.com/a/58582651/1939576
      EXTRA_FLAGS: "--traverse-namespace"
      NP_BUILD_DEP: "numpy==1.18"
      NP_TEST_DEP: "numpy==1.18"
    - PYTHON: C:\Python38-x64
      EXTRA_FLAGS: "--traverse-namespace"
      NP_BUILD_DEP: "numpy==1.18"
      NP_TEST_DEP: "numpy==1.18"
    - PYTHON: C:\Python39
      EXTRA_FLAGS: "--traverse-namespace"
      NP_BUILD_DEP: "numpy==1.20"
      NP_TEST_DEP: "numpy==1.20"
    - PYTHON: C:\Python39-x64
      EXTRA_FLAGS: "--traverse-namespace"
      NP_BUILD_DEP: "numpy==1.20"
      NP_TEST_DEP: "numpy==1.20"

install:
  # Prepend newly installed Python to the PATH of this build (this cannot be
  # done from inside the powershell script as it would require to restart
  # the parent CMD process).
  - SET PATH=%PYTHON%;%PYTHON%\Scripts;%PATH%
  - python -m pip install -U pip setuptools

  # Fix MSVC builds for 64-bit Python. See:
  # http://stackoverflow.com/questions/32091593/cannot-install-windows-sdk-7-1-on-windows-10
  - echo "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64 > "C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC\bin\amd64/vcvars64.bat"

  # Install the dependencies of the project.
  - pip install %NP_BUILD_DEP% Cython nose nibabel sympy scipy
  # Pin wheel to 0.26 to avoid Windows ABI tag for built wheel
  - pip install wheel==0.26
  # Build wheel
  - cd nipy
  - git submodule update --init
  - git checkout %BUILD_COMMIT%
  - python setup.py bdist_wheel
  - cd ..

build: false  # Not a C# project, build stuff at the test step instead.

test_script:
  - pip install %NP_TEST_DEP%
  - pip install --pre --no-index --find-links .\nipy\dist nipy
  # Change into an innocuous directory and find tests from installation
  - mkdir for_testing
  - cd for_testing
  - python --version
  - python ..\nipy\tools\nipnost %EXTRA_FLAGS% nipy
  - cd ..

artifacts:
  # Archive the generated wheel package in the ci.appveyor.com build report.
  - path: nipy\dist\*

on_success:
  # Upload the generated wheel package to Anaconda.org
  - pip install git+https://github.com/Anaconda-Platform/anaconda-project
  - pip install git+https://github.com/Anaconda-Platform/anaconda-client
  - anaconda -t %ANACONDA_SECRET% upload --force -u %ANACONDA_ORG% nipy\dist\*.whl

cache:
  # Use the appveyor cache to avoid re-downloading large archives such
  # the MKL numpy and scipy wheels mirrored on a rackspace cloud
  # container, speed up the appveyor jobs and reduce bandwidth
  # usage on our rackspace account.
  - '%APPDATA%\pip\Cache'
